---
title: "What Is the Prostate?"
bibliography: prostate_blog.bib
csl: nature.csl
format: html
---

## Introduction

The prostate is a small accessory gland in the male reproductive system
that is present in all mammals[jin_prostate_nodate; ittmann_anatomy_2018]^1,2^. It sits just below the bladder and
wraps around the top of the urethra^3,4^. In humans it\'s roughly the
size of a walnut and is made up of glandular tissue, smooth muscle, and
connective tissue^1,4^. In normal human physiology, the prostate
performs several distinct functions in the body, from producing
prostatic fluid, a key component of semen, to physically regulating the
switch between urination and ejaculation^5,6^.

## The Function

The primary role of the prostate is to produce and secrete prostatic
fluid, which constitutes about 25-30% of the total semen volume^7^. This
fluid contains multiple components including zinc which serves to
stabilize the DNA found in sperm cells and various enzymes that support
sperm survival, transport, and fertilization^1,8^. Prostate-specific
antigen (PSA) and other proteases enable the liquefaction of semen after
ejaculation, thereby allowing sperm to swim more freely^9,10^. This
function of the prostate is just one step of the coordinated process
that produces semen but the specialized compounds in the prostatic fluid
protect sperm and increases the likelihood of successful
fertilization^1^.

Beyond its role in producing prostatic fluid, the prostate also
functions as a mechanical switch between urination and
ejaculation^11,12^. This is driven by two muscle systems running
adjacent and parallel to the prostatic urethra, the urethral dilator
(musculus dilatator urethrae) and musculus ejaculatorius^11^. The
coordinated activation of these muscles alters the shape of the prostate
which facilitates the switch between ejaculation and urination
states^11,13,14^. During urination, contraction of the urethral dilator
muscle shortens the prostatic urethra and alters the orientation and
shape of the prostate. As a result, the prostatic urethral lumen widens,
facilitating the passage of urine from the bladder into the
urethra^11,13,14^. During ejaculation, sympathetic activation initiates
a coordinated contractile response involving the musculus ejaculatorius
and smooth muscle of the reproductive tract, including the vas deferens,
seminal vesicles, and prostate^7,15^. Simultaneously, contraction of the
bladder neck prevents retrograde ejaculation into the bladder^7^.
Prostatic and ejaculatory duct contractions then deliver seminal fluid
into the urethra, while coordinated pelvic floor contractions propel
semen distally through the penile urethra^7,16^. The prostate also
functions to control semen release via coordinated smooth-muscle cell
contractions that compress the glandular ducts of the prostate which
pushes prostatic fluid into the urethra and helps mix prostatic
secretions with sperm and seminal vesicle fluid^17,18^. This also
contributes to the forward movement of semen through the urethra^7^.

Additionally, the prostate contributes to prevent infections of the
urinary and reproductive tracts^19--21^. Through the urethra, the
prostate is exposed to the outside world and encounters bacteria which
is dealt with through the prostate's built-in defense mechanisms. High
accumulations of zinc in the prostate provide a natural antimicrobial
environment^8^. Zinc contributes to antimicrobial defense by inhibiting
bacterial enzymes, disrupting bacterial metabolism, and limiting overall
bacterial growth^22--24^. There are also immune cells present in the
prostate which enable immune surveillance and the detection of
infections^25--27^.

## Anatomy

The prostate is a pyramid-shaped organ located below the bladder^28^.
The base of the prostate sits against the bladder with the apex facing
downwards^28^. A normal prostate weighs about 15-20g^28^. The prostate
can be divided into four zones or regions: the peripheral zone (PZ), the
central zone (CZ), the transition zone (TZ), and the fibromuscular
region^4,29^. The peripheral zone makes up \>70% of the prostate
glandular tissue, with the central zone and transition zone making up
\~25% and \~5%, respectively^4^. The fibromuscular region sits at the
front of the prostate and contains muscle and fibrous tissue instead of
glandular cells^4^. The peripheral zone is typically where prostate
cancer develops with about 70-80% of cancer originating from this
zone^29^. Prostate cancer can arise from the central and transition
zones but occurs at lower rates^29^. The transition zone grows
throughout life and this causes the disease of benign prostatic
hyperplasia (BPH)^30^.

The prostate is a branched tubuloalveolar exocrine gland, meaning it
contains secretory units (acini) and branching ducts that function to
produce prostatic fluid^31,32^. The acini are small pouch-shaped
glandular units lining a central lumen and are responsible for producing
and secreting prostatic fluid into the lumen^28^. Once this fluid is
secreted into the lumen it drains through the system of branching
epithelial ducts and tubules which all converge to the prostatic
urethra^28^. Together, the acini and ducts make up the prostate
epithelium, which is traditionally classified into three types of
epithelial cells: luminal, basal, and neuroendocrine^28^.

The luminal epithelial cells are terminally differentiated specialized
secretory epithelial cells^33^. They have a columnar shape and line the
lumen of the prostate^33^. These cells express markers specific to
luminal epithelial cells including cytokeratin (CK) CK8 and CK18, AR,
and AR targets like KLK3^33^. The primary function of the luminal cells
is to produce the proteins and compounds that comprise prostatic
fluid^33^.

The basal epithelial cells are found between the luminal epithelial
cells and adjacent to the basement membrane^33^. These cells provide
structural support to the tissue by anchoring luminal epithelial cells
to the basement membrane^33^. They also function as progenitor cells to
regenerate the glandular epithelium after an injury^33^. Basal cells
have a flattened morphology and distinct cell markers^33^. These markers
include CK5, CK14, TP63, and very low to no AR expression^33^. Due to
this low expression of AR, these cells do not need androgens to survive
and grow^33^.

The neuroendocrine epithelial cells are found rarely dispersed among the
luminal and basal epithelial cells^34^. They are reported to make up
about 1% of the cells in the epithelium^34^. The function of
neuroendocrine cells is to sense pH and chemical changes and regulate
growth via various growth factors as they have been found to have a
secretory function^34^. They have an elongated morphology, lack AR
expression, and express neuroendocrine-lineage markers such as
chromogranin A (CHGA), synaptophysin (SYP), and neuron-specific enolase
(NSE)^34^.

More recent research has identified additional epithelial cell types
beyond the traditional categories^33^. There have been multiple reports
of mixed cell types where cells express markers of more than one cell
type (e.g. luminal and basal markers)^33^. Additionally, there have been
non-canonical epithelial cell types identified in the human prostate
that resemble the morphology and transcriptomic profiles of club and
hillock cells of the respiratory tract^33^. The exact roles of these
cells in the prostate are still largely unknown but new research
suggests they play a similar role of immune modulation and lineage
plasticity^33^.

The stroma of the prostate is fibromuscular, and it includes
fibroblasts, smooth muscle cells, endothelial cells, nerves, and
assorted infiltrating cells (e.g., mast cells, lymphocytes)^35^. There
is no adipose tissue in the prostate^28^. The epithelial cells in the
prostate receive nutrients and hormones through the stroma cells^36^.
Cellular communication among epithelial cells and stromal cells plays a
strong role in regulated function in the prostate^35,36^.

## Conclusion

## The prostate is a complex organ that plays an important role in male urinary and sexual function^37^. Across the world, prostate cancer is one of the most common cancer types^38^. In the next post, I will discuss prostate cancer etiology and tumorigenesis.

## References
[References]{.underline}

1\. Simoes, G. F., Sakuramoto, P., dosSantos, C. B., Furlan, N. K. C. &
Augusto, T. M. An Overview on Prostate Pathophysiology: New Insights
into Prostate Cancer Clinical Diagnosis. in *Pathophysiology - Altered
Physiological States* (IntechOpen, 2018). doi:10.5772/intechopen.74269.

2\. Vásquez, B. Morphological Characteristics of Prostate in Mammals.
*Int. J. Med. Surg. Sci.* **1**, 63--72 (2014).

3\. Aaron, L., Franco, O. E. & Hayward, S. W. Review of Prostate Anatomy
and Embryology and the Etiology of Benign Prostatic Hyperplasia. *Urol.
Clin. North Am.* **43**, 279--288 (2016).

4\. Bhavsar, A. & Verma, S. Anatomic Imaging of the Prostate. *BioMed
Res. Int.* **2014**, 728539 (2014).

5\. Lang, R. J. & Hashitani, H. Role of prostatic interstitial cells in
prostate motility. *J. Smooth Muscle Res.* **53**, 57--72 (2017).

6\. Risbridger, G. P. & Taylor, R. A. CHAPTER 23 - Physiology of the
Male Accessory Sex Structures: The Prostate Gland, Seminal Vesicles, and
Bulbourethral Glands. in *Knobil and Neill's Physiology of Reproduction
(Third Edition)* (ed. Neill, J. D.) 1149--1172 (Academic Press, St
Louis, 2006). doi:10.1016/B978-012515400-0/50028-2.

7\. Revenig, L., Leung, A. & Hsiao, W. Ejaculatory physiology and
pathophysiology: assessment and treatment in male infertility. *Transl.
Androl. Urol.* **3**, 419--449 (2014).

8\. Costello, L. C. & Franklin, R. B. A comprehensive review of the role
of zinc in normal prostate function and metabolism; and its implications
in prostate cancer. *Arch. Biochem. Biophys.* **611**, 100--112 (2016).

9\. Robert, M., Gibbs, B. F., Jacobson, E. & Gagnon, C. Characterization
of Prostate-Specific Antigen Proteolytic Activity on its Major
Physiological Substrate, the Sperm Motility Inhibitor
Precursor/Semenogelin I. *Biochemistry* **36**, 3811--3819 (1997).

10\. Balk, S. P., Ko, Y.-J. & Bubley, G. J. Biology of Prostate-Specific
Antigen. *J. Clin. Oncol.* **21**, 383--391 (2003).

11\. Dorschner, W., Stolzenburg, J.-U. & Mondry, J. Anatomy of the Lower
Urinary Tract. *Videourology^TM^* **24**, vid.2009.0027 (2010).

12\. A New Theory of Micturition and Urinary Continence Based on
Histomorphological Studies \| Urologia Internationalis \| Karger
Publishers.
https://karger.com/uin/article/52/4/189/306627/A-New-Theory-of-Micturition-and-Urinary-Continence.

13\. Hocaoglu, Y. *et al.* Real-time magnetic resonance imaging (MRI):
anatomical changes during physiological voiding in men. *BJU Int.*
**109**, 234--239 (2012).

14\. Contraction of the anterior prostate is required for the initiation
of micturition - Hocaoglu - 2013 - BJU International - Wiley Online
Library.
https://bjui-journals.onlinelibrary.wiley.com/doi/10.1111/j.1464-410X.2012.11698.x.

15\. Physiology of Male Sexual Function \| Annals of Internal Medicine.
https://www.acpjournals.org/doi/10.7326/0003-4819-92-2-329.

16\. Human Ejaculatory Duct: Parameters of Smooth Muscle Motor Activity
and Modulatory Role of Autonomic Drugs - Mancinelli - 2000 -
Experimental Physiology - Wiley Online Library.
https://physoc.onlinelibrary.wiley.com/doi/10.1111/j.1469-445X.2000.00356.x.

17\. Kügler, R. *et al.* Novel imaging of the prostate reveals
spontaneous gland contraction and excretory duct quiescence together
with different drug effects. *FASEB J.* **32**, 1130--1138 (2018).

18\. Role of prostatic interstitial cells in prostate motility.
https://www.jstage.jst.go.jp/article/jsmr/53/0/53_0478/\_article.

19\. Quintar, A. A. & Maldonado, C. A. Androgen regulation of host
defenses and response to inflammatory stimuli in the prostate gland.
*Cell Biol. Int.* **41**, 1223--1233 (2017).

20\. Silva, J. A. *et al.* Prostate immunology: A challenging puzzle.
https://doi.org/10.1016/j.jri.2020.103190 (2020)
doi:10.1016/j.jri.2020.103190.

21\. Townes, C. L. *et al.* Prostate specific antigen enhances the
innate defence of prostatic epithelium against Escherichia coli
infection. *The Prostate* **73**, 1529--1537 (2013).

22\. McDevitt, C. A. *et al.* A Molecular Mechanism for Bacterial
Susceptibility to Zinc. *PLOS Pathog.* **7**, e1002357 (2011).

23\. Ong, C. Y., Walker, M. J. & McEwan, A. G. Zinc disrupts central
carbon metabolism and capsule biosynthesis in Streptococcus pyogenes.
*Sci. Rep.* **5**, 10799 (2015).

24\. Cuajungco, M. P., Ramirez, M. S. & Tolmasky, M. E. Zinc:
Multidimensional Effects on Living Organisms. *Biomedicines* **9**, 208
(2021).

25\. Bostwick, D. G., de la Roza, G., Dundore, P., Corica, F. A. &
Iczkowski, K. A. Intraepithelial and stromal lymphocytes in the normal
human prostate. *The Prostate* **55**, 187--193 (2003).

26\. Fox, J. J., Navarro, H. I., Hashimoto, T., Garcia, A. & Goldstein,
A. Mass cytometry reveals species-specific differences and a new level
of complexity for immune cells in the prostate. *Am. J. Clin. Exp.
Urol.*
https://www.semanticscholar.org/paper/Mass-cytometry-reveals-species-specific-differences-Fox-Navarro/59ba92b636e4da76c6681a79594280e39572c062
(2019).

27\. Tuong, Z. K. *et al.* Resolving the immune landscape of human
prostate at a single-cell level in health and cancer. *Cell Rep.*
**37**, 110132 (2021).

28\. Ittmann, M. Anatomy and Histology of the Human and Murine Prostate.
*Cold Spring Harb. Perspect. Med.* **8**, a030346 (2018).

29\. Verma, S. & Rajesh, A. A Clinically Relevant Approach to Imaging
Prostate Cancer: Review. *Am. J. Roentgenol.* **196**, S1--S10 (2011).

30\. The Origin and Development of Benign Prostatic Hyperplasia An
Age‐Dependent Process - OESTERLING - 1991 - Journal of Andrology - Wiley
Online Library.
https://onlinelibrary.wiley.com/doi/10.1002/j.1939-4640.1991.tb00271.x.

31\. Francis, J. C. & Swain, A. Prostate Organogenesis. *Cold Spring
Harb. Perspect. Med.* **8**, a030353 (2018).

32\. Köseoǧlu, H. Prostate Stones. in *Evolving Trends in Urology*
(IntechOpen, 2012). doi:10.5772/37153.

33\. Pitzen, S. P. & Dehm, S. M. Basal epithelial cells in prostate
development, tumorigenesis, and cancer progression. *Cell Cycle* **22**,
1303--1318.

34\. Butler, W. & Huang, J. Neuroendocrine cells of the prostate:
Histology, biological functions, and molecular mechanisms. *Precis.
Clin. Med.* **4**, 25--34 (2021).

35\. Hägglöf, C. & Bergh, A. The Stroma---A Key Regulator in Prostate
Function and Malignancy. *Cancers* **4**, 531--548 (2012).

36\. Denmeade, S. R. & Isaacs, J. T. Cellular Organization of the Normal
Prostate. in *Holland-Frei Cancer Medicine. 6th edition* (BC Decker,
2003).

37\. M.D, L. C. What is a prostate, and what does it do? *UT MD
Anderson*
https://www.mdanderson.org/cancerwise/what-is-a-prostate\--and-what-does-it-do.h00-159699912.html.

38\. Schafer, E. J. *et al.* Recent Patterns and Trends in Global
Prostate Cancer Incidence and Mortality: An Update. *Eur. Urol.* **87**,
302--313 (2025).
